### ISSUE TITLE
System did't booting

### ISSUE THREAD

**Issue by Bagunda** [itemir/rpi_boat_utils#2]
After "sudo ./uart_control default" and reboot RPI 3 cant boot.
In HDMI printing "fixing recursive fault but reboot is needed".
Reboots don't help

**Comment by itemir** [comment]
What version of Raspbian is this?

**Comment by Bagunda** [comment]
Finally on this time.
But not Raspbian. Openhabian

**Comment by Bagunda** [comment]
I insert SSD in another RPI, mounting first partition, edit config.txt and deleted line "enable_uart=1".
And RPI booting normaly.
