### ISSUE TITLE
Send AIS messages to multiple IP addresses

### ISSUE THREAD

**Issue by va2sie** [itemir/rpi_boat_utils#3]
In AISPlay, is it possible to send the AIS messages over UDP to multiple IP addresses? (ex: MarineTraffic, AISHub, etc.) 
If so, how should the command be entered? 

Thanks in advance for your help!

**Comment by itemir** [comment]
I think what you are looking for is aisdispatcher: http://www.aishub.net/ais-dispatcher

**Comment by itemir** [comment]
I will close this. Follow-up if aisdispatcher doesn't address your need.

**Comment by va2sie** [comment]
Thanks @itemir  !
