### ISSUE TITLE
uart_control fails on Ubuntu 20.10

### ISSUE THREAD

**Issue by ytechie** [itemir/rpi_boat_utils#7]
In Ubuntu 20.10, the `config.txt` and `cmdline.txt` files have moved under a `firmware` subdirectory. Changing these lines in the script is a temporary workaround:

```
  CONFIG=/boot/firmware/config.txt
  CMDLINE=/boot/firmware/cmdline.txt
```

**Comment by itemir** [comment]
Thanks Jason. To clarify, this tool is for Raspberry Pi running Raspbian, so could you elaborate?

**Comment by ytechie** [comment]
I didn't realize that. On older versions of Ubuntu, those file paths matched Raspbian, so it would have worked on either OS.

I'm running Ubuntu server on my Pi.

I actually don't need the script anymore, it was just for a quick test. I just wanted to let you know that if it does detect the OS, you can make it work on both OS's on the Pi. Up to you. Feel free to close if you prefer.

Thanks!

**Comment by itemir** [comment]
Thank you Jason. This makes sense. However, I would like to keep this simple. Supporting multiple Raspberry Pis on multiple OSes increase the testing complexity a fair bit. So I will close this.
